export const CREATE_PASSENGER = "CREATE_PASSENGER";
export const RETRIEVE_PASSENGERS = "RETRIEVE_PASSENGERS";
export const RETRIEVE_PASSENGER = "RETRIEVE_PASSENGER";
export const UPDATE_PASSENGER = "UPDATE_PASSENGER";
export const DELETE_PASSENGER = "DELETE_PASSENGER";

export const CREATE_AIRLINE = "CREATE_AIRLINE";
export const RETRIEVE_AIRLINE = "RETRIEVE_AIRLINE";
export const RETRIEVE_AIRLINES = "RETRIEVE_AIRLINES";

export const PASSENGER_LIST_REQUEST = "PASSENGER_LIST_REQUEST";
export const PASSENGER_LIST_SUCCESS = "PASSENGER_LIST_SUCCESS";
export const PASSENGER_LIST_FAIL = "PASSENGER_LIST_FAIL";

export const PASSENGER_CREATE_REQUEST = "PASSENGER_CREATE_REQUEST";
export const PASSENGER_CREATE_SUCCESS = "PASSENGER_CREATE_SUCCESS";
export const PASSENGER_CREATE_FAIL = "PASSENGER_CREATE_FAIL";
export const PASSENGER_CREATE_RESET = "PASSENGER_CREATE_RESET";

export const PASSENGER_UPDATE_REQUEST = "PASSENGER_UPDATE_REQUEST";
export const PASSENGER_UPDATE_SUCCESS = "PASSENGER_UPDATE_SUCCESS";
export const PASSENGER_UPDATE_FAIL = "PASSENGER_UPDATE_FAIL";
export const PASSENGER_UPDATE_RESET = "PASSENGER_UPDATE_RESET";
